version: 2.1

jobs:
  build:
    working_directory: ~/udagram-microservices

    docker:
      - image: circleci/node:14

    steps:
      - checkout

      - run:
          name: Check versions
          command: |
            docker --version
            docker-compose --version

      - run:
          name: Build images
          command: |
            docker image prune --all
            docker-compose -f docker-compose-build.yaml build --parallel
            docker tag udagram-frontend nvfede/udagram-frontend
            docker tag udagram-api-feed nvfede/udagram-api-feed
            docker tag udagram-api-user nvfede/udagram-api-user
            docker tag udagram-reverseproxy nvfede/udagram-reverseproxy

      - run:
          name: Push images
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push nvfede/udagram-frontend
            docker push nvfede/udagram-api-feed
            docker push nvfede/udagram-api-user
            docker push nvfede/udagram-reverseproxy
    environment:
      DOCKER_USERNAME: "$DOCKER_USERNAME"
      DOCKER_PASSWORD: "$DOCKER_PASSWORD"
