version: 2.1

jobs:
  build:
    working_directory: ~/repo

    docker:
      - image: circleci/node:13

    steps:
      - checkout

      - run:
          name: Check versions
          command: |
            docker --version
            docker-compose --version

      - run:
          name: Build images
          command: |
            docker image prune --all
            docker-compose -f docker-compose-build.yaml build --parallel

      - run:
          name: Push images
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push rasterayzer/udagram-frontend
            docker push rasterayzer/udagram-api-feed
            docker push rasterayzer/udagram-api-user
            docker push rasterayzer/udagram-reverseproxy
    environment:
      DOCKER_USERNAME: "$DOCKER_USERNAME"
      DOCKER_PASSWORD: "$DOCKER_PASSWORD"
